## Vector datasets and file structure

Vector datasets store geometries together with attribute data in a table-like structure.
Each row represents a geographic feature, while one column contains the geometry and the remaining columns store descriptive attributes.

Vector data represents  geographic features and is commonly stored in formats such as Shapefiles or GeoPackages.
These formats define how geometries, attributes, and coordinate reference systems are stored.

**Import required packages**

GeoKit is imported to provide the required functionality for working with vector data.

In [11]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import geokit as gk

### Shapefiles

A Shapefile is a widely used vector data format for storing points, lines, or polygons together with attribute information.
Although often referred to as a single file, a Shapefile actually consists of multiple files that must always be kept together.

All files share the same base name and together form one vector dataset.
Removing or renaming individual files may make the dataset unusable.

**Required components**

- `.shp` – stores the geometry data (coordinates)
- `.dbf` – stores the attribute table (non-spatial information such as names or values)
- `.shx` – index file linking geometries to attributes and enabling fast access

**Optional but common components**

- `.prj` – stores coordinate reference system (CRS) information

In [12]:
import pathlib
from geokit.core.get_test_data import get_test_data

# Path to cache folder
data_cache_folder = pathlib.Path().cwd().parent.parent.joinpath("geokit", "data") 

# Path to shapefile folder
gadm36_DEU_1_path = get_test_data(
    file_name="gadm36_DEU_1.shp",
    data_cache_folder=data_cache_folder,
)

# Load vector dataset from a Shapefile and reproject to EPSG:4326
federal_states_DE = gk.vector.extractFeatures(gadm36_DEU_1_path)

 # show dataset
federal_states_DE

,geom,GID_0,NAME_0,GID_1,NAME_1,VARNAME_1,NL_NAME_1,TYPE_1,ENGTYPE_1,CC_1,HASC_1
0,"MULTIPOLYGON (((8.70802116 47.6895752,8.707655...",DEU,Germany,DEU.1_1,Baden-Württemberg,None,None,Land,State,08,DE.BW
1,"POLYGON ((9.74066353 47.55353546,9.74057579 47...",DEU,Germany,DEU.2_1,Bayern,Bavaria,None,Freistaat,None,09,DE.BY
2,"POLYGON ((13.17135715 52.3977623,13.17135334 5...",DEU,Germany,DEU.3_1,Berlin,None,None,Land,State,11,DE.BE
3,"MULTIPOLYGON (((12.26715565 52.2313118,12.2704...",DEU,Germany,DEU.4_1,Brandenburg,None,None,Land,State,12,DE.BR
4,"MULTIPOLYGON (((8.71142387 53.04463196,8.71033...",DEU,Germany,DEU.5_1,Bremen,None,None,Freie Hansestadt,State,04,DE.HB
5,"MULTIPOLYGON (((10.21060085 53.52004623,10.211...",DEU,Germany,DEU.6_1,Hamburg,None,None,Freie und Hansestadt,State,02,DE.HH
6,"MULTIPOLYGON (((8.68058777 49.62247086,8.68134...",DEU,Germany,DEU.7_1,Hessen,Hesse,None,Land,State,06,DE.HE
7,"MULTIPOLYGON (((11.4958334 54.03180695,11.4958...",DEU,Germany,DEU.8_1,Mecklenburg-Vorpommern,Mecklenburg-West Pomerania,None,Land,State,13,DE.MV
8,"MULTIPOLYGON (((6.76194477 53.61875153,6.76194...",DEU,Germany,DEU.9_1,Niedersachsen,Lower Saxony,None,Land,State,03,DE.NI
9,"POLYGON ((8.05965614 50.69504166,8.0413866 50....",DEU,Germany,DEU.10_1,Nordrhein-Westfalen,North Rhine-Westphalia,None,Land,State,05,DE.NW
10,"POLYGON ((6.6504283 49.54951096,6.65105438 49....",DEU,Germany,DEU.11_1,Rheinland-Pfalz,Rhineland-Palatinate,None,Land,State,07,DE.RP
11,"POLYGON ((6.84392643 49.15551376,6.84085464 49...",DEU,Germany,DEU.12_1,Saarland,None,None,Land,State,10,DE.SL
12,"POLYGON ((14.79049587 50.82408524,14.79012299 ...",DEU,Germany,DEU.14_1,Sachsen,Saxony,None,Freistaat,State,14,DE.SN
13,"MULTIPOLYGON (((11.44027328 51.19976044,11.441...",DEU,Germany,DEU.13_1,Sachsen-Anhalt,Saxony-Anhalt,None,Land,State,15,DE.ST
14,"MULTIPOLYGON (((9.53010368 53.67519379,9.53016...",DEU,Germany,DEU.15_1,Schleswig-Holstein,None,None,Land,State,01,DE.SH
15,"POLYGON ((11.70222759 50.40244293,11.70159817 ...",DEU,Germany,DEU.16_1,Thüringen,Thuringia,None,Freistaat,State,16,DE.TH

### GeoPackages

A GeoPackage is a vector data format designed to store geospatial data in a single file.
Unlike Shapefiles, all geometries, attributes, and spatial reference information are stored together in one file with the extension `.gpkg`.

A GeoPackage can contain multiple vector layers, making it suitable for more complex datasets and workflows.

**Key characteristics**

- Stored as a single `.gpkg` file
- Can contain multiple vector layers
- Supports different geometry types and complex attributes
- Stores coordinate reference system (CRS) information internally

When working with GeoPackages in GeoKit, a specific layer can be selected if the file contains more than one layer.

In [13]:
# Path to gpkg folder
gadm36_DEU_1_path = "/fast/home/d-marmullaku/Projects/Hackathon_2/geokit/geokit/data/gadm36_DEU_1.gpkg"

# Load vector dataset from a gpgk file for a specific layer 
federal_states_DE = gk.vector.extractFeatures(gadm36_DEU_1_path, layerName="gadm_DEU_level1")

 # show dataset
federal_states_DE

,geom,GID_0,NAME_0,GID_1,NAME_1,VARNAME_1,NL_NAME_1,TYPE_1,ENGTYPE_1,CC_1,HASC_1
0,"MULTIPOLYGON (((8.70802116 47.6895752,8.707655...",DEU,Germany,DEU.1_1,Baden-Württemberg,None,None,Land,State,08,DE.BW
1,"MULTIPOLYGON (((9.74066353 47.55353546,9.74057...",DEU,Germany,DEU.2_1,Bayern,Bavaria,None,Freistaat,None,09,DE.BY
2,"MULTIPOLYGON (((13.17135715 52.3977623,13.1713...",DEU,Germany,DEU.3_1,Berlin,None,None,Land,State,11,DE.BE
3,"MULTIPOLYGON (((12.26715565 52.2313118,12.2704...",DEU,Germany,DEU.4_1,Brandenburg,None,None,Land,State,12,DE.BR
4,"MULTIPOLYGON (((8.71142387 53.04463196,8.71033...",DEU,Germany,DEU.5_1,Bremen,None,None,Freie Hansestadt,State,04,DE.HB
5,"MULTIPOLYGON (((10.21060085 53.52004623,10.211...",DEU,Germany,DEU.6_1,Hamburg,None,None,Freie und Hansestadt,State,02,DE.HH
6,"MULTIPOLYGON (((8.68058777 49.62247086,8.68134...",DEU,Germany,DEU.7_1,Hessen,Hesse,None,Land,State,06,DE.HE
7,"MULTIPOLYGON (((11.4958334 54.03180695,11.4958...",DEU,Germany,DEU.8_1,Mecklenburg-Vorpommern,Mecklenburg-West Pomerania,None,Land,State,13,DE.MV
8,"MULTIPOLYGON (((6.76194477 53.61875153,6.76194...",DEU,Germany,DEU.9_1,Niedersachsen,Lower Saxony,None,Land,State,03,DE.NI
9,"MULTIPOLYGON (((8.05965614 50.69504166,8.04138...",DEU,Germany,DEU.10_1,Nordrhein-Westfalen,North Rhine-Westphalia,None,Land,State,05,DE.NW
10,"MULTIPOLYGON (((6.6504283 49.54951096,6.651054...",DEU,Germany,DEU.11_1,Rheinland-Pfalz,Rhineland-Palatinate,None,Land,State,07,DE.RP
11,"MULTIPOLYGON (((6.84392643 49.15551376,6.84085...",DEU,Germany,DEU.12_1,Saarland,None,None,Land,State,10,DE.SL
12,"MULTIPOLYGON (((14.79049587 50.82408524,14.790...",DEU,Germany,DEU.14_1,Sachsen,Saxony,None,Freistaat,State,14,DE.SN
13,"MULTIPOLYGON (((11.44027328 51.19976044,11.441...",DEU,Germany,DEU.13_1,Sachsen-Anhalt,Saxony-Anhalt,None,Land,State,15,DE.ST
14,"MULTIPOLYGON (((9.53010368 53.67519379,9.53016...",DEU,Germany,DEU.15_1,Schleswig-Holstein,None,None,Land,State,01,DE.SH
15,"MULTIPOLYGON (((11.70222759 50.40244293,11.701...",DEU,Germany,DEU.16_1,Thüringen,Thuringia,None,Freistaat,State,16,DE.TH

### Analylze vector data

In [14]:
vinfo = gk.vector.vectorInfo(gadm36_DEU_1_path)

 # show information about the vector dataset
print("COUNT", vinfo.count)

print("SRS", vinfo.srs)

print("ATTRIBUTES", vinfo.attributes)

COUNT 16
SRS GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AXIS["Latitude",NORTH],
    AXIS["Longitude",EAST],
    AUTHORITY["EPSG","4326"]]
ATTRIBUTES ['GID_0', 'NAME_0', 'GID_1', 'NAME_1', 'VARNAME_1', 'NL_NAME_1', 'TYPE_1', 'ENGTYPE_1', 'CC_1', 'HASC_1']